repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.5.7'
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
    - id: mypy
